global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'openruntime'
    static_configs:
      - targets: ['openruntime:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'gpu-exporter'
    static_configs:
      - targets: ['gpu-exporter:9400']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093