name: Performance Monitoring

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  performance-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run performance tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        # Start server
        python openruntime_enhanced.py &
        SERVER_PID=$!
        sleep 15
        
        # Run comprehensive performance tests
        python scripts/stress_test.py --concurrent 20 --total 1000 > perf_results.txt
        
        # Run GPU benchmarks
        curl -X POST "http://localhost:8000/benchmark?benchmark_type=comprehensive" | jq '.' > gpu_benchmark.json
        
        # Kill server
        kill $SERVER_PID
        
        # Generate performance report
        python scripts/generate_perf_report.py
    
    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results-${{ github.run_id }}
        path: |
          perf_results.txt
          gpu_benchmark.json
          performance_report.html
    
    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const results = fs.readFileSync('perf_results.txt', 'utf8');
          const body = `## Performance Test Results\n\n\`\`\`\n${results}\n\`\`\``;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });